# Generated by Django 4.0.3 on 2022-03-27 14:58

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guestCanPause',
            new_name='guest_can_pause',
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=app.models.generateUniqueCode, max_length=8, unique=True),
        ),
    ]
